#!/usr/bin/env bash
# This script displays list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy

echo "PID   USER      %CPU %MEM COMMAND"
echo "----------------------------------"

ps axjf | awk '{ printf "%-5s %-10s %-5s %-5s %s\n", $1, $3, $4, $5, $9 }'
