#!/usr/bin/env bash
#Bash script that displays messages when read some signals

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid && exit' SIGQUIT SIGTERM

# display message
echo "To infinity and beyond indefinitely"

# infinite loop
while true; do
    sleep 1
done
